# Generated by Django 3.2.5 on 2022-07-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_settings_per_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('general practitioner', 'General Practitioner'), ('podiatrist', 'Podiatris'), ('peditrician', 'Peditrician'), ('endocrinologist', 'Endocrinologist'), ('neurologist', 'Neurologist'), ('rheumatologist', 'Rheumatologist'), ('allergist', 'Allergist'), ('psychiatrist', 'Psychiatrist'), ('nephrologist', 'Nephrologist'), ('surgeon', 'Surgeon'), ('oncologist', 'Oncologist'), ('dermatologist', 'Dermatologist'), ('radiologist', 'Radiologist'), ('cardiologist', 'Cardiologist'), ('dentist', 'Dentist')], max_length=25, null=True)),
                ('frequency_of_AP_per_2hours', models.IntegerField()),
                ('doctor_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aps_per_station', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filled_date_time_choices_per_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField()),
                ('booked_time', models.TimeField(choices=[('07:00:00', '07hours'), ('09:00:00', '09hours'), ('11:00:00', '11hours'), ('13:00:00', '13hours'), ('15:00:00', '15hours')])),
                ('aps_per_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment_settings_per_station')),
            ],
        ),
        migrations.CreateModel(
            name='Filled_date_choices_per_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField()),
                ('aps_per_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment_settings_per_station')),
            ],
        ),
        migrations.CreateModel(
            name='Booked_appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.TimeField(choices=[('07:00:00', '07hours'), ('09:00:00', '09hours'), ('11:00:00', '11hours'), ('13:00:00', '13hours'), ('15:00:00', '15hours')])),
                ('appointment_date', models.DateField()),
                ('doctor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_booked_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Available_time_choices_per_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_appointment_time', models.TimeField(choices=[('07:00:00', '07hours'), ('09:00:00', '09hours'), ('11:00:00', '11hours'), ('13:00:00', '13hours'), ('15:00:00', '15hours')])),
                ('aps_per_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment_settings_per_station')),
            ],
        ),
    ]
