# Generated by Django 3.2.5 on 2022-02-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_settings_per_station',
            name='appointment_type',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
