# Generated by Django 3.2.5 on 2022-02-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_settings_per_station_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_time_choices_per_station',
            name='available_appointment_time',
            field=models.TimeField(choices=[('08:00', '08:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('16:00', '16:00')]),
        ),
        migrations.AlterField(
            model_name='booked_appointments',
            name='appointment_time',
            field=models.TimeField(choices=[('08:00', '08:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('16:00', '16:00')]),
        ),
    ]
