# Generated by Django 3.2.5 on 2022-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20220213_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_time_choices_per_station',
            name='available_appointment_time',
            field=models.TimeField(choices=[('08:00', '08hours'), ('10:00', '10hours'), ('12:00', '12hours'), ('14:00', '14hours'), ('16:00', '16hours')]),
        ),
        migrations.AlterField(
            model_name='booked_appointments',
            name='appointment_time',
            field=models.TimeField(choices=[('08:00', '08hours'), ('10:00', '10hours'), ('12:00', '12hours'), ('14:00', '14hours'), ('16:00', '16hours')]),
        ),
    ]
