# Generated by Django 3.2.5 on 2022-02-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20220214_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filled_date_time_choices_per_station',
            old_name='booked_dates',
            new_name='booked_date',
        ),
    ]
