# Generated by Django 3.2.5 on 2022-02-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_rename_booked_dates_filled_date_time_choices_per_station_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filled_date_time_choices_per_station',
            name='is_filled',
        ),
        migrations.CreateModel(
            name='Filled_date_choices_per_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField()),
                ('aps_per_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment_settings_per_station')),
            ],
        ),
    ]
