# Generated by Django 3.2.5 on 2022-02-27 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0008_auto_20220223_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_settings_per_station',
            name='doctor_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aps_per_station', to=settings.AUTH_USER_MODEL),
        ),
    ]
