# Generated by Django 3.2.5 on 2022-03-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_settings_per_station_doctor_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_settings_per_station',
            name='appointment_type',
            field=models.CharField(choices=[('general practitioner', 'General Practitioner'), ('podiatrist', 'Podiatris'), ('peditrician', 'Peditrician'), ('endocrinologist', 'Endocrinologist'), ('neurologist', 'Neurologist'), ('rheumatologist', 'Rheumatologist'), ('allergist', 'Allergist'), ('psychiatrist', 'Psychiatrist'), ('nephrologist', 'Nephrologist'), ('surgeon', 'Surgeon'), ('oncologist', 'Oncologist'), ('dermatologist', 'Dermatologist'), ('radiologist', 'Radiologist'), ('cardiologist', 'Cardiologist'), ('dentist', 'Dentist')], max_length=25, null=True),
        ),
    ]
