# Generated by Django 3.2.5 on 2022-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20220314_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_time_choices_per_station',
            name='available_appointment_time',
            field=models.TimeField(choices=[('07:00', '07hours'), ('09:00', '09hours'), ('11:00', '11hours'), ('13:00', '13hours'), ('15:00', '15hours')]),
        ),
        migrations.AlterField(
            model_name='booked_appointments',
            name='appointment_time',
            field=models.TimeField(choices=[('07:00', '07hours'), ('09:00', '09hours'), ('11:00', '11hours'), ('13:00', '13hours'), ('15:00', '15hours')]),
        ),
        migrations.AlterField(
            model_name='filled_date_time_choices_per_station',
            name='booked_time',
            field=models.TimeField(choices=[('07:00', '07hours'), ('09:00', '09hours'), ('11:00', '11hours'), ('13:00', '13hours'), ('15:00', '15hours')]),
        ),
    ]
