version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=doc_app
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
      dockerfile: Dockerfile  
    depends_on:
      - postgres  
    ports:
      - "8000:8000"
      - "3000:3000"
    entrypoint: ["/bin/bash"]
    command: ["-c","make start-django-server"]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
