version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=doc_app
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "3000:3000"
    command: ["make django-makemigrations","make django-migrate"]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
