# Generated by Django 3.2.5 on 2022-03-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'a_positive'), ('A-', 'a_negative'), ('B+', 'b_positive'), ('B-', 'b_negative'), ('AB+', 'AB_POSITIVE'), ('AB-', 'ab_negative'), ('O+', 'o_positive'), ('0-', 'o_negative')], max_length=16, null=True),
        ),
    ]
