export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCCES = 'LOGIN_SUCCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const USER_RELOAD = 'USER_RELOADED';
export const GET_ERRORS = 'GET_ERRORS';

export const AVAILABLE_APPOITMENTS = 'AVAILABLE_APPOITMENTS';
export const AVAILABLE_APPOITMENTS_FAILED = 'AVAILABLE_APPOITMENTS_FAILED';
export const GET_APPOITMENTS_SETTINGS = 'GET_APPOITMENTS_SETTINGS';
export const GET_APPOITMENTS_SETTINGS_FAILED = 'GET_APPOITMENTS_SETTINGS_FAILED';
export const GET_AVAILABLE_APPOITMENTS_TIME = 'GET_AVAILABLE_APPOITMENTS_TIME';
export const GET_AVAILABLE_APPOITMENTS_TIME_FAILED = 'GET_AVAILABLE_APPOITMENTS_TIME_FAILED';

export const GET_DOC_APPOITMENTS = 'GET_DOC_APPOITMENTS';
export const GET_DOC_APPOITMENTS_FAILED = 'GET_DOC_APPOITMENTS_FAILED';

export const ADD_APPOITMENTS_SETTINGS = 'ADD_APPOITMENTS_SETTING';
export const ADD_APPOITMENTS_SETTINGS_FAILED = 'ADD_APPOITMENTS_SETTING_FAILED';
export const ADD_APPOITMENT= 'ADD_APPOITMENT';
export const ADD_APPOITMENT_FAILED = 'ADD_APPOITMENT_FAILED';

export const ADD_BLOG = 'ADD_BLOG';
export const ADD_BLOG_FAILED = 'ADD_BLOG_FAILED';
export const GET_BLOGS = 'GET_BLOGS';
export const GET_BLOGS_FAILED = 'GET_BLOGS_FAILED';

export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_FAILED = 'GET_REVIEWS_FAILED';
export const GET_USER_REVIEW = 'GET_USER_REVIEWS';
export const GET_USER_REVIEW_FAILED = 'GET_USER_REVIEWS_FAILED';
export const POST_REVIEW = 'POST_REVIEW';
export const POST_REVIEW_FAILED = 'POST_REVIEW_FAILED';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const UPDATE_REVIEW_FAILED = 'UPDATE_REVIEW_FAILED';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';
export const GET_COMMENTS_FOR_COMMENTS = 'GET_COMMENTS_FOR_COMMENTS';
export const GET_COMMENTS_FOR_COMMENTS_FAILED = 'GET_COMMENTS_FOR_COMMENTS_FAILED';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENTS_FAILED = 'ADD_COMMENTS_FAILED';
export const ADD_COMMENTS_FOR_COMMENTS = 'ADD_COMMENTS_FOR_COMMENTS';
export const ADD_COMMENTS_FOR_COMMENTS_FAILED = 'ADD_COMMENTS_FOR_COMMENTS_FAILED';
export const CLEAR_COMMENTS='CLEAR_COMMENTS'
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const UPDATE_COMMENTS_FAILED = 'UPDATE_COMMENTS_FAILED';
export const UPDATE_COMMENT_FOR_COMMENT = 'UPDATE_COMMENTS_FOR_COMMENTS';
export const UPDATE_COMMENT_FOR_COMMENT_FAILED = 'UPDATE_COMMENTS_FOR_COMMENTS_FAILED';
// export const LOADED_FAILED = 'LOADED_FAILED';
