# Generated by Django 3.2.5 on 2021-07-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_patient',
        ),
    ]
