# Generated by Django 3.2.5 on 2022-07-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('neurological', 'Neurological'), ('pediatrics', 'Pediatrics'), ('urogenital', 'Urogenital'), ('ophthalmology', 'Ophthalmology'), ('allergy and immunology', 'Allergy Ang Immunology'), ('psychiatry', 'Psychiatry'), ('oral', 'Oral'), ('surgery', 'Surgery'), ('urology', 'Urology'), ('dermatology', 'Dermatology'), ('pathology', 'Pathology'), ('cardiology', 'Cardiology'), ('dentistry', 'Dentistry')], max_length=25)),
                ('date_posted', models.DateTimeField()),
                ('last_date_modified', models.DateTimeField()),
                ('blog_title', models.CharField(max_length=25)),
                ('blog_content', models.CharField(max_length=2000)),
                ('thumbnail', models.ImageField(null=True, upload_to='blog-thumbnails')),
                ('excerpt', models.CharField(max_length=150, null=True)),
                ('blogger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_for_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_comment', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('from_original', models.BooleanField(default=False)),
                ('commentor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs')),
                ('commentor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
