# Generated by Django 3.2.5 on 2022-03-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_content',
            field=models.CharField(max_length=2000),
        ),
    ]
