# Generated by Django 3.2.5 on 2022-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date_posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_date_modified',
            field=models.DateTimeField(),
        ),
    ]
