# Generated by Django 3.2.5 on 2022-03-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220316_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='excerpt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='blog-thumbnails'),
        ),
    ]
