# Generated by Django 3.2.5 on 2022-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
